name: test_action

on: [push, pull_request]

jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
   - name: checkout repo content
     uses: actions/checkout@v2
   - name: setup python
     uses: actions/setup-python@v2
     with:
       python-version: 3.7.6
   - name: run test script
     run: |
       python setup.py install
       pip install ipython
       pip install numpy=1.19.1
       pip install scipy=1.5.2
       pip install numba==0.51.2
       pip install matplotlib
       python tests/runAllTests.py
